/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mendezdavidp03;

import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    
    MyList lista = new MyList();
    boolean aceptarMode = false;
    
    public Interfaz() {
        initComponents();
        
        
        lista.add(new Empleado(1, "David", 9, 1, 2004, 1350, 19));
        lista.add(new Empleado(2, "Juan", 29, 10, 1997, 1200, 29));
        lista.add(new Empleado(3, "Pablo", 5, 6, 1999, 1250, 23));
        lista.add(new Empleado(4, "Alberto", 27, 11, 1979, 1500, 45));
        lista.add(new Empleado(5, "Pedro", 30, 9, 1984, 1300, 33));
        
        mostrarEmpleado();
        buttonAceptar.setEnabled(false);
        buttonCancelar.setEnabled(false);
        botonAnterior.setEnabled(false);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreL = new javax.swing.JLabel();
        numeroL = new javax.swing.JLabel();
        fechaAltaL = new javax.swing.JLabel();
        sueldoL = new javax.swing.JLabel();
        edadL = new javax.swing.JLabel();
        numeroF = new javax.swing.JTextField();
        nombreF = new javax.swing.JTextField();
        fechaAltaDia = new javax.swing.JTextField();
        sueldoF = new javax.swing.JTextField();
        edadF = new javax.swing.JTextField();
        botonAnterior = new javax.swing.JButton();
        botonCrear = new javax.swing.JButton();
        botonSiguiente = new javax.swing.JButton();
        fechaAltaMes = new javax.swing.JTextField();
        fechaAltaAnio = new javax.swing.JTextField();
        buttonAceptar = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();
        buttonBorrar = new javax.swing.JButton();
        buttonModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombreL.setText("Nombre: ");

        numeroL.setText("Número: ");

        fechaAltaL.setText("Fecha de Alta: ");

        sueldoL.setText("Sueldo: ");

        edadL.setText("Edad: ");

        numeroF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroFActionPerformed(evt);
            }
        });

        sueldoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sueldoFActionPerformed(evt);
            }
        });

        botonAnterior.setText("Anterior");
        botonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnteriorActionPerformed(evt);
            }
        });

        botonCrear.setText("Crear");
        botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearActionPerformed(evt);
            }
        });

        botonSiguiente.setText("Siguiente");
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });

        buttonAceptar.setText("Aceptar");
        buttonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAceptarActionPerformed(evt);
            }
        });

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        buttonBorrar.setText("Borrar");
        buttonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBorrarActionPerformed(evt);
            }
        });

        buttonModificar.setText("Modificar");
        buttonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buttonModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(buttonAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numeroL, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nombreL, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fechaAltaL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sueldoL, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(edadL, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(botonAnterior, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreF)
                    .addComponent(sueldoF)
                    .addComponent(edadF)
                    .addComponent(numeroF)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fechaAltaDia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fechaAltaMes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fechaAltaAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonCrear, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(buttonBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroL)
                    .addComponent(numeroF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreL)
                    .addComponent(nombreF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaAltaL)
                    .addComponent(fechaAltaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaAltaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaAltaAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sueldoL)
                    .addComponent(sueldoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edadL)
                    .addComponent(edadF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAnterior)
                    .addComponent(botonCrear)
                    .addComponent(botonSiguiente))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAceptar)
                    .addComponent(buttonCancelar)
                    .addComponent(buttonBorrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(buttonModificar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numeroFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroFActionPerformed

    private void sueldoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sueldoFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sueldoFActionPerformed

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
        borrarDatos();
        buttonAceptar.setEnabled(true);
        buttonCancelar.setEnabled(true);
        botonAnterior.setEnabled(false);
        botonSiguiente.setEnabled(false);
        botonCrear.setEnabled(false);
        buttonBorrar.setEnabled(false);
        buttonModificar.setEnabled(false);
        
        aceptarMode = false;
        
        
    }//GEN-LAST:event_botonCrearActionPerformed

    private void botonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnteriorActionPerformed
        lista.retroceder();
        
        mostrarEmpleado();
        
        if(lista.isLast())
        {
            botonAnterior.setEnabled(false);
        }
        botonSiguiente.setEnabled(true);
        
    }//GEN-LAST:event_botonAnteriorActionPerformed

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed
        lista.avanzar();

        mostrarEmpleado();
        
        if(lista.isFirst())
        {
            botonSiguiente.setEnabled(false);
        }
        botonAnterior.setEnabled(true);
        
    }//GEN-LAST:event_botonSiguienteActionPerformed

    private void buttonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAceptarActionPerformed
       
            crearEmpleado();
            mostrarEmpleado();
        
            if(aceptarMode == false)
            {
                botonAnterior.setEnabled(false);

            }
            else
            {
                botonAnterior.setEnabled(true);

            }
            buttonAceptar.setEnabled(false);
            buttonCancelar.setEnabled(false);
            botonSiguiente.setEnabled(true);
            botonCrear.setEnabled(true);
            buttonBorrar.setEnabled(true);
            buttonModificar.setEnabled(true);
       
    }//GEN-LAST:event_buttonAceptarActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        mostrarEmpleado();
        buttonAceptar.setEnabled(false);
        buttonCancelar.setEnabled(false);
        botonAnterior.setEnabled(true);
        botonSiguiente.setEnabled(true);
        botonCrear.setEnabled(true);
        buttonBorrar.setEnabled(true);
        buttonModificar.setEnabled(true);
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void buttonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModificarActionPerformed
        buttonAceptar.setEnabled(true);
        buttonCancelar.setEnabled(true);
        botonAnterior.setEnabled(false);
        botonSiguiente.setEnabled(false);
        botonCrear.setEnabled(false);
        buttonBorrar.setEnabled(false);
        buttonModificar.setEnabled(false);
        
        aceptarMode = true;
    }//GEN-LAST:event_buttonModificarActionPerformed

    private void buttonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBorrarActionPerformed
        borrarEmpleado();
    }//GEN-LAST:event_buttonBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });  
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAnterior;
    private javax.swing.JButton botonCrear;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JButton buttonAceptar;
    private javax.swing.JButton buttonBorrar;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonModificar;
    private javax.swing.JTextField edadF;
    private javax.swing.JLabel edadL;
    private javax.swing.JTextField fechaAltaAnio;
    private javax.swing.JTextField fechaAltaDia;
    private javax.swing.JLabel fechaAltaL;
    private javax.swing.JTextField fechaAltaMes;
    private javax.swing.JTextField nombreF;
    private javax.swing.JLabel nombreL;
    private javax.swing.JTextField numeroF;
    private javax.swing.JLabel numeroL;
    private javax.swing.JTextField sueldoF;
    private javax.swing.JLabel sueldoL;
    // End of variables declaration//GEN-END:variables

    public void borrarEmpleado()
    {
        if(lista.isFirst())
        {
            lista.removeElement();
            lista.retroceder();
            mostrarEmpleado();
        }
        else if(lista.isLast())
        {
            lista.removeElement();
            lista.avanzar();
            mostrarEmpleado();
        }
        else
        {
            lista.removeElement();
            lista.avanzar();
            mostrarEmpleado();
        }
            if(lista.isFirst() && lista.isLast())
            {
                botonSiguiente.setEnabled(false);
                botonAnterior.setEnabled(false);
                buttonBorrar.setEnabled(false);
            }
            
    }
    
    public void mostrarEmpleado()
    {
        Empleado e1 = (Empleado) lista.getActualNode().getMain();
        numeroF.setText(""+ e1.getNum());
        nombreF.setText(e1.getNombre());
        fechaAltaDia.setText(""+ e1.getFechaAlta().getDia());
        fechaAltaMes.setText(""+ e1.getFechaAlta().getMes());
        fechaAltaAnio.setText(""+ e1.getFechaAlta().getAnio());
        sueldoF.setText(""+ e1.getSueldo());
        edadF.setText("" + e1.getEdad());
    }
    
    public void crearEmpleado()
    {
        
        
        if((Integer.parseInt(fechaAltaDia.getText()) < 1 || Integer.parseInt(fechaAltaDia.getText()) > 31) && (Integer.parseInt(fechaAltaMes.getText()) < 1 || Integer.parseInt(fechaAltaMes.getText()) > 12))
        {
           JOptionPane.showMessageDialog(this, "Día y mes introducidos no son válidos"); 
        }
        else
        {
            if(Integer.parseInt(fechaAltaDia.getText()) < 1 || Integer.parseInt(fechaAltaDia.getText()) > 31)
            {
                JOptionPane.showMessageDialog(this, "El día de alta introducido no es válido.");
            }
            else
            {
                if(Integer.parseInt(fechaAltaMes.getText()) < 1 || Integer.parseInt(fechaAltaMes.getText()) > 12)
                {
                    JOptionPane.showMessageDialog(this, "El mes de alta introducido no es válido.");
                }
                else
                {
                    if(aceptarMode == false)
                    {
                        lista.add(new Empleado(Integer.parseInt(numeroF.getText()), nombreF.getText(), Integer.parseInt(fechaAltaDia.getText()), Integer.parseInt(fechaAltaMes.getText()), Integer.parseInt(fechaAltaAnio.getText()), Integer.parseInt(sueldoF.getText()), Integer.parseInt(edadF.getText())));
                        botonAnterior.setEnabled(false);
                    }
                    else
                    {
                        
                        lista.getActualNode().setMain(new Empleado(Integer.parseInt(numeroF.getText()), nombreF.getText(), Integer.parseInt(fechaAltaDia.getText()), Integer.parseInt(fechaAltaMes.getText()), Integer.parseInt(fechaAltaAnio.getText()), Integer.parseInt(sueldoF.getText()), Integer.parseInt(edadF.getText())));
                    }
                }
            }
        }
    }
    
    
    public void borrarDatos()
    {
        numeroF.setText("");
        nombreF.setText("");
        sueldoF.setText("");
        edadF.setText("");
        fechaAltaDia.setText("");
        fechaAltaMes.setText("");
        fechaAltaAnio.setText("");
    }
    
    
}
